[package]
name = "newton-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
anyhow = "1.0.75"
log = "0.4.20"
num-complex = "0.4.4"
palette = "0.7.3"
